name: Teste com Robot Framework

on: 
  workflow_dispatch

jobs:
  run_automation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar Dependências do Python
      run: |
        sudo apt update
        sudo apt install -y python3.10 python3.10-venv python3.10-dev

    - name: Verificar Versão do Python
      run: python3 --version

    - name: Configurar ambiente virtual e instalar dependências
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar Testes
      run: |
        mkdir -p results
        source venv/bin/activate
        robot -d ./results ./tests/test_integration.robot

    - name: Upload dos Resultados dos Testes
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: results
        path: results

  generate_report:
    if: always()
    needs: [run_automation] 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Baixar Resultados dos Testes
      uses: actions/download-artifact@v3
      with:
        name: results

    - name: Gerar e Enviar Relatório
      uses: Gabriel/robotframework-reporter-action@v2
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
