name: Teste com Robot Framework

on: 
  workflow_dispatch  # Permite executar manualmente

permissions:
  contents: read
  pull-requests: write

jobs:
  run_automation:
    runs-on: ubuntu-latest
    
    steps:
    # --- PASSO 1: PREPARAÇÃO ---
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Verificar estrutura (debug)
      run: ls -R 

    - name: Limpar resultados anteriores
      run: |
        echo "🔄 Apagando resultados antigos..."
        rm -rf test/results/* || true 

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Criar pasta de resultados
      run: mkdir -p test/results  

    - name: Executar Testes
      run: |
        echo "🚀 Iniciando testes..."
        cd test/ && robot -d ./results ./test_integration.robot

    - name: Upload dos Resultados
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: test/results/*
        if-no-files-found: error  
        
  generate_report:
    needs: [run_automation]
    runs-on: ubuntu-latest 
    steps:
    - name: Baixar resultados
      uses: actions/download-artifact@v4
      with:
        name: robot-results
        path: results
    - name: Exibir resumo (debug)
      run: |
        echo "📊 Relatório gerado em:"
        ls -la results/