name: Teste com Robot Framework

on: 
  workflow_dispatch

permissions:
  contents: read
  issues: write
  pull-requests: write
  
jobs:
  run_automation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Verificar estrutura do repositório
      run: ls -R  # Lista todos os arquivos e pastas para debug

    - name: Criar diretório de resultados
      run: mkdir -p results

    - name: Configurar ambiente virtual e instalar dependências
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar Testes
      run: |
        source venv/bin/activate
        cd test/ && robot -d ./results ./test_integration.robot

    - name: Upload dos Resultados dos Testes
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: results
        path: test/results

  generate_report:
    if: always()
    needs: [run_automation] 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Baixar Resultados dos Testes
      uses: actions/download-artifact@v4
      with:
        name: results
        path: reports

    - name: Gerar e Enviar Relatório
      uses: Gabriel/robotframework-reporter-action@v2
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
